HELP = {
    "LIHAT": "Menampilkan isi direktori",
    "MASUK": "Masuk ke direktori",
    "MUNDUR": "Kembali ke direktori sebelumnya",
    "POSISI": "Menampilkan path saat ini",
    "BUKA": "Membuat direktori",
    "BAKAR": "Menghapus direktori",
    "KEBUN": "Menampilkan struktur direktori",
    "TANAM": "Membuat file kosong",
    "PANEN": "Membaca isi file",
    "RAWAT": "Edit file (akhiri dengan :simpan)",
    "TEBANG": "Menghapus file",
    "CANGKOK": "Copy file",
    "PINDAH": "Pindahkan file",
    "BERSIHKAN": "Membersihkan layar terminal",
    "PULANG": "Keluar dari SaWiTOS",
    "SIAPA": "Menampilkan user aktif",
    "INFO_SAWIT": "Informasi sistem",
    "BANTUAN": "Menampilkan semua command",
    "SAWIT": "Command rahasia 🌴"
}
